# spring.application.name=foodapp
# spring.datasource.url=jdbc:postgresql://localhost:5432/paf
# spring.datasource.username=postgres
# spring.datasource.password=2002
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.properties.hibernate.format_sql=true

spring.application.name=backend
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lesson
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File Upload Size (optional)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# File Upload
file.upload-dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/
